import {
    AppConfigurationPayload,
    HuggingFaceModelCatalogResponse,
    HuggingFaceModelDefinition,
    NodeManifest,
    OllamaLibraryCatalogResponse,
    ProviderCapability,
    ProviderCatalogResponse,
} from '../workflow/schema/types'

export function createNodeManifest(overrides: Partial<NodeManifest> = {}): NodeManifest {
    return {
        id: 'PROMPT',
        version: 1,
        name: 'Prompt',
        category: 'prompt',
        description: 'Static prompt',
        inputs: [],
        outputs: [
            {
                name: 'text',
                data_type: 'TEXT',
                required: true,
                accepts_multiple: false,
                description: 'Prompt text',
            },
        ],
        controllers: [],
        parameters: [
            {
                name: 'prompt_text',
                data_type: 'TEXT',
                default: 'hello',
                constraints: {},
                ui_control: 'text',
                description: 'Prompt value',
            },
        ],
        ui: {
            default_width: 320,
            accent_color: '#4aa3ff',
            collapsed_by_default: false,
        },
        runtime: {
            executor_key: 'prompt',
            cacheable: false,
            deterministic: true,
            side_effecting: false,
            destructive: false,
            idempotent: false,
            plugin: null,
        },
        ...overrides,
    }
}

export function createConfigurationPayload(overrides: Partial<AppConfigurationPayload> = {}): AppConfigurationPayload {
    return {
        session_name: 'default',
        provider_configurations: [
            {
                provider: 'openai',
                api_key: 'sk-test',
                has_api_key: true,
                base_url: null,
                metadata: {},
            },
            {
                provider: 'huggingface',
                api_key: 'hf-test',
                has_api_key: true,
                base_url: null,
                metadata: {},
            },
            {
                provider: 'ollama',
                api_key: null,
                has_api_key: false,
                base_url: 'http://127.0.0.1:11434',
                metadata: {
                    chat_model: 'llama3.2',
                    embedding_model: 'nomic-embed-text',
                },
            },
        ],
        ...overrides,
    }
}

export function createProviderCatalog(
    providers?: ProviderCapability[],
): ProviderCatalogResponse {
    return {
        providers: providers || [
            {
                provider: 'ollama',
                label: 'Ollama',
                configuration_kind: 'local',
                model_source: 'live',
                default_base_url: 'http://127.0.0.1:11434',
                default_chat_model: 'llama3.2',
                default_embedding_model: 'nomic-embed-text',
                requires_api_key: false,
                supports_status_check: true,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'openai',
                label: 'OpenAI',
                configuration_kind: 'cloud',
                model_source: 'hosted_registry',
                default_base_url: 'https://api.openai.com/v1',
                default_chat_model: null,
                default_embedding_model: null,
                requires_api_key: true,
                supports_status_check: false,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'gemini',
                label: 'Google Gemini',
                configuration_kind: 'cloud',
                model_source: 'hosted_registry',
                default_base_url: 'https://generativelanguage.googleapis.com/v1beta',
                default_chat_model: null,
                default_embedding_model: null,
                requires_api_key: true,
                supports_status_check: false,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'claude',
                label: 'Anthropic Claude',
                configuration_kind: 'cloud',
                model_source: 'hosted_registry',
                default_base_url: 'https://api.anthropic.com/v1',
                default_chat_model: null,
                default_embedding_model: null,
                requires_api_key: true,
                supports_status_check: false,
                supports_chat: true,
                supports_embeddings: false,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'deepseek',
                label: 'DeepSeek',
                configuration_kind: 'cloud',
                model_source: 'hosted_registry',
                default_base_url: 'https://api.deepseek.com',
                default_chat_model: null,
                default_embedding_model: null,
                requires_api_key: true,
                supports_status_check: false,
                supports_chat: true,
                supports_embeddings: false,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'huggingface',
                label: 'Hugging Face',
                configuration_kind: 'remote',
                model_source: 'downloaded_filesystem',
                default_base_url: null,
                default_chat_model: null,
                default_embedding_model: null,
                requires_api_key: true,
                supports_status_check: false,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: false,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'lmstudio',
                label: 'LM Studio',
                configuration_kind: 'local',
                model_source: 'live',
                default_base_url: 'http://localhost:1234/v1',
                default_chat_model: 'local-model',
                default_embedding_model: 'local-embedding-model',
                requires_api_key: false,
                supports_status_check: true,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
            {
                provider: 'llama',
                label: 'llama.cpp',
                configuration_kind: 'local',
                model_source: 'live',
                default_base_url: 'http://localhost:8080/v1',
                default_chat_model: 'local-model',
                default_embedding_model: 'local-embedding-model',
                requires_api_key: false,
                supports_status_check: true,
                supports_chat: true,
                supports_embeddings: true,
                supports_structured_output: true,
                supports_streaming: true,
                supports_tool_calling: false,
                supports_tool_selection: true,
                supports_native_tool_protocol: false,
            },
        ],
    }
}

export function createOllamaCatalog(overrides?: Partial<OllamaLibraryCatalogResponse>): OllamaLibraryCatalogResponse {
    return {
        models: [
            {
                model: 'llama3.2',
                description: 'General purpose local model',
                homepage: 'https://ollama.com/library/llama3.2',
                pulled: false,
            },
        ],
        total_count: 1,
        pulled_count: 0,
        refreshed_at: '2026-03-24T00:00:00Z',
        source: 'stub',
        ...overrides,
    }
}

export function createHuggingFaceModel(overrides?: Partial<HuggingFaceModelDefinition>): HuggingFaceModelDefinition {
    return {
        repo_id: 'acme/model',
        author: 'acme',
        task: 'text-generation',
        library: 'transformers',
        likes: 1,
        downloads: 10,
        visibility: 'public',
        private: false,
        gated: false,
        last_modified: '2026-03-24T00:00:00Z',
        url: 'https://huggingface.co/acme/model',
        downloaded: false,
        size_bytes: 1024,
        ...overrides,
    }
}

export function createHuggingFaceCatalog(
    models: HuggingFaceModelDefinition[],
    overrides?: Partial<HuggingFaceModelCatalogResponse>,
): HuggingFaceModelCatalogResponse {
    return {
        models,
        page: 1,
        page_size: 25,
        has_more: false,
        using_token: false,
        warning: null,
        available_tasks: ['text-generation'],
        available_libraries: ['transformers'],
        ...overrides,
    }
}
